[identities]
vcs = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCgJkeHi1A+ERs+vDAGzs8rQfHjSzRym7S+jGz4rYXgweRgMKqn0mp5OXy5MGGZDijzbHSVXRpe27Kh9M35ETlnttqWMnj1XAVPE/jraQ6x0qgrfsD1PqNrNPgqHm8LJhxhmTATI1FP2g/ivx9G+0CWG8l9W+7UOdX/gGNSsakp9lX6csm36okDUemZErWbkygSq+puh0kT/zoCzd81VilHF58iMMSA8A/hUpUCJK3vMiNNK0lyoE2JShpe3CL5ze7fTkcw/JW33NE08HnGOKe34a0Q1W4G0FsY8FX/HpHq1GMium7yhANW9fCP8wY/di2QE11OH6CE9PIQO7ngXrjOzo/tUGWCjuSWFKWQx6QC17zWTQcDOyotgBnlGeCkcfSdveZuiJ7kPgRKAWiMV2IwDDmIVxVVTdPtVHFTmrbzEsZObW4SJL7I2aOHo+f5AEIBcVP8NWw0fmD7RZenIMrNlzPpoIWNBX/RAHBus8TfwYD437gxsfcpiTNzYfbEzOYsPst/AM2pK9l0V9bcbfWLM7S3Q5Ev4j2fGUn9U6vDbJ3NwS+JV5WV5B/ZADTjbCrwqbJrQUytLZ74phq14qK99CKBlWwsjblEQTqUNYtJ7wfuWHrxlEuN3xHvUhuMcBa14lfDgDe2ollet1mDbDIKHwpJgcwYHR0sgFL4JfeBEQ=="

[[paths]]
glob = "secrets/*"
identities = [ "vcs" ]
