# https://github.com/cole-h/agenix-cli/blob/main/.agenix.toml.example
# https://github.com/ryantm/agenix?tab=readme-ov-file#tutorial
[identities]
bak = "age1REPLACE3"
twopi-root = "age1REPLACE1"
twopi-dani = "age1REPLACE2"

[[paths]]
glob = "secrets/twopi/*"
identities = [ "bak", "twopi-root" ]
