name: CI
on:
  push:
  schedule:
    - cron: 0 0 * * 1

jobs:
  nix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nix-command:
          - flake check
          - build .#homeConfigurations."tobias@gamer".activationPackage
          - build .#homeConfigurations."tobhap@M386".activationPackage
          #- build .#nixOnDroidConfigurations.oneplus5.activationPackage
          - build .#nixosConfigurations.krypton.config.system.build.toplevel
          - build .#nixosConfigurations.neon.config.system.build.toplevel
          #- build .#nixosConfigurations.xenon.config.system.build.toplevel
          - run .#format
          - develop .#jdk8 --profile profile
          - develop .#jdk11 --profile profile
          - develop .#jdk15 --profile profile
          - develop .#jdk17 --profile profile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v16

      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: gerschtli
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: Build command
        run: |
          nix \
            --log-format bar-with-logs \
            --option keep-going true \
            --show-trace \
            ${{ matrix.nix-command }}

# vim: set sw=2:
