name: Build and test flake outputs
on:
  push:
  workflow_call:
    inputs:
      branch:
        description: Branch name to build on
        default: ''
        required: false
        type: string
    secrets:
      CACHIX_SIGNING_KEY:
        required: true

jobs:
  nix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        system:
          - aarch64
          - x86_64
        nix-command:
          - run .#ci-build -- packages.$_system.rpi-firmware
          #- flake check # temporarily disabled because of failing nixGL evaluation on aarch64
          - fmt
          - eval .#apps.$_system.ci-build.program
          - eval .#apps.$_system.setup.program

        include:
          - system: x86_64
            nix-command: flake check

          - nix-command: develop .#jdk8 --profile profile
            system: x86_64
          - nix-command: develop .#jdk11 --profile profile
            system: x86_64
          - nix-command: develop .#jdk15 --profile profile
            system: x86_64
          - nix-command: develop .#jdk17 --profile profile
            system: x86_64
          - nix-command: develop .#php74 --profile profile
            system: x86_64
          - nix-command: develop .#php80 --profile profile
            system: x86_64
          - nix-command: develop .#php81 --profile profile
            system: x86_64

          - nix-command: run .#ci-build -- 'homeConfigurations."tobias@gamer".activationPackage'
            system: x86_64
          - nix-command: run .#ci-build -- 'homeConfigurations."tobhap@M386".activationPackage'
            system: x86_64

          - nix-command: run .#ci-build -- nixOnDroidConfigurations.oneplus5.activationPackage
            system: aarch64

          - nix-command: run .#ci-build -- nixosConfigurations.argon.config.system.build.toplevel
            system: aarch64
          - nix-command: run .#ci-build -- nixosConfigurations.krypton.config.system.build.toplevel
            system: x86_64
          - nix-command: run .#ci-build -- nixosConfigurations.neon.config.system.build.toplevel
            system: x86_64
          - nix-command: run .#ci-build -- nixosConfigurations.xenon.config.system.build.toplevel
            system: aarch64

          - nix-command: run .#ci-build -- packages.$_system.rpi-image
            system: aarch64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Install nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            keep-going = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: gerschtli
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: Build command (aarch64)
        if: matrix.system == 'aarch64'
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: alpine_latest
          githubToken: ${{ github.token }}
          dockerRunArgs: --volume /nix:/nix
          install: apk --no-cache add curl git xz
          env: |
            _system: ${{ matrix.system }}-linux
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            set -euo pipefail

            mkdir -p /etc/nix
            echo "max-jobs = auto" >> /etc/nix/nix.conf
            echo "trusted-users = root" >> /etc/nix/nix.conf
            echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
            echo "build-users-group =" >> /etc/nix/nix.conf
            echo "keep-going = true" >> /etc/nix/nix.conf
            echo "access-tokens = github.com=$GITHUB_TOKEN" >> /etc/nix/nix.conf
            export USER=root

            echo "::group::Install nix"
            sh <(curl -L https://nixos.org/nix/install) --no-channel-add
            . ${HOME}/.nix-profile/etc/profile.d/nix.sh

            # setting build-hook is needed because default hook `nix __build-remote` is not available
            function build_hook() {
              local nix_path="$(which nix)"
              echo "${nix_path/bin\/nix/libexec/nix/build-remote}"
            }
            echo "build-hook = $(build_hook)" >> /etc/nix/nix.conf

            echo "::group::Setup cachix"
            nix --print-build-logs run nixpkgs#cachix -- use gerschtli 2>&1 | cat # this is needed to fake non-tty for stderr for pretty build logs
            nix --print-build-logs run nixpkgs#cachix -- use nix-on-droid 2>&1 | cat # this is needed to fake non-tty for stderr for pretty build logs

            echo "::group::Build command"
            git config --global --add safe.directory "$(pwd)"

            nix \
              --print-build-logs \
              --show-trace \
              ${{ matrix.nix-command }} \
              2>&1 | cat # this is needed to fake non-tty for stderr for pretty build logs

      - name: Build command (x86_64)
        if: matrix.system == 'x86_64'
        env:
          _system: ${{ matrix.system }}-linux
        run: |
          nix \
            --show-trace \
            ${{ matrix.nix-command }}

  deploy:
    runs-on: ubuntu-latest
    needs: nix
    if: github.ref == 'refs/heads/master' && inputs.branch == ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: gerschtli
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: Deploy cachix-agent spec
        env:
          CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN }}
        run: |
          nix run .#ci-build -- packages.x86_64-linux.cachix-deploy-spec
          spec="$(nix build --print-out-paths .#cachix-deploy-spec)"
          cachix push gerschtli "$spec"
          cachix deploy activate "$spec"

# vim: set sw=2:
