name: Build and test flake outputs
on:
  push:
  workflow_call:
    inputs:
      branch:
        description: Branch name to build on
        default: ''
        required: false
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  nix:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        system:
          - aarch64
        include:
          - nix-command: build .#nixOnDroidConfigurations.sams9.activationPackage --impure --argstr system aarch64-linux
            system: aarch64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Install nix
        uses: cachix/install-nix-action@v17
        with:
          install_url: "https://releases.nixos.org/nix/nix-2.9.2/install"

      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: 573-bc
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build command (aarch64)
        if: matrix.system == 'aarch64'
        run: nix \
               --log-format bar-with-logs \
               --option keep-going true \
               --show-trace \
               ${{ matrix.nix-command }}

# vim: set sw=2:
