name: Build and test flake outputs
on:
  push:
  workflow_call:
    inputs:
      branch:
        description: Branch name to build on
        default: ''
        required: false
        type: string
    secrets:
      CACHIX_SIGNING_KEY:
        required: true

jobs:
  nix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        system:
          - aarch64
          - x86_64
        nix-command:
          - run .#ci-build -- packages.$_system.rpi-firmware
          #- flake check # FIXME: temporarily disabled because of failing nixGL evaluation on aarch64
          - fmt
          - eval .#apps.$_system.ci-build.program
          - eval .#apps.$_system.setup.program

        include:
          - system: x86_64
            nix-command: flake check

          - nix-command: develop .#jdk8 --profile profile
            system: x86_64
          - nix-command: develop .#jdk11 --profile profile
            system: x86_64
          - nix-command: develop .#jdk15 --profile profile
            system: x86_64
          - nix-command: develop .#jdk17 --profile profile
            system: x86_64
          - nix-command: develop .#php74 --profile profile
            system: x86_64
          - nix-command: develop .#php80 --profile profile
            system: x86_64
          - nix-command: develop .#php81 --profile profile
            system: x86_64

          - nix-command: run .#ci-build -- 'homeConfigurations."tobias@gamer".activationPackage'
            system: x86_64
          - nix-command: run .#ci-build -- 'homeConfigurations."tobhap@M386".activationPackage'
            system: x86_64

          - nix-command: run .#ci-build -- nixOnDroidConfigurations.oneplus5.activationPackage
            system: aarch64

          - nix-command: run .#ci-build -- nixosConfigurations.argon.config.system.build.toplevel
            system: aarch64
            deploy-spec: .#cachix-deploy-spec-argon
          - nix-command: run .#ci-build -- nixosConfigurations.krypton.config.system.build.toplevel
            system: x86_64
            deploy-spec: .#cachix-deploy-spec-krypton
          - nix-command: run .#ci-build -- nixosConfigurations.neon.config.system.build.toplevel
            system: x86_64
            deploy-spec: .#cachix-deploy-spec-neon
          - nix-command: run .#ci-build -- nixosConfigurations.xenon.config.system.build.toplevel
            system: aarch64
            deploy-spec: .#cachix-deploy-spec-xenon

          - nix-command: run .#ci-build -- packages.$_system.rpi-image
            system: aarch64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Install nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            keep-going = true
            show-trace = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: gerschtli
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: Build command (aarch64)
        if: matrix.system == 'aarch64'
        # FIXME: use upstream once --tty is removed
        #uses: uraimo/run-on-arch-action@v2
        uses: Gerschtli/run-on-arch-action@tty
        with:
          arch: aarch64
          distro: alpine_latest
          githubToken: ${{ github.token }}
          dockerRunArgs: --volume /nix:/nix
          install: apk --no-cache add curl git xz
          env: |
            _system: ${{ matrix.system }}-linux
            CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN || 'no-value' }}
            CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
            DEPLOY_SPEC: ${{ matrix.deploy-spec || 'no-value' }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            USER: root
          run: |
            set -euo pipefail

            mkdir -p /etc/nix

            cat <<EOF >> /etc/nix/nix.conf
            max-jobs = auto
            trusted-users = root
            experimental-features = nix-command flakes
            build-users-group =
            keep-going = true
            show-trace = true
            access-tokens = github.com=$GITHUB_TOKEN
            EOF

            echo "::group::Install nix"
            INSTALL_FILE="install"
            curl \
              --silent \
              --show-error \
              --output "$INSTALL_FILE" \
              --retry 5 \
              --retry-all-errors \
              --fail \
              --location \
              "https://nixos.org/nix/install"

            sh "$INSTALL_FILE" --no-channel-add
            rm "$INSTALL_FILE"
            . ${HOME}/.nix-profile/etc/profile.d/nix.sh

            # FIXME: setting build-hook is needed because default hook `nix __build-remote` is not available
            function build_hook() {
              local nix_path="$(which nix)"
              echo "${nix_path/bin\/nix/libexec/nix/build-remote}"
            }
            echo "build-hook = $(build_hook)" >> /etc/nix/nix.conf


            echo "::group::Setup cachix"
            nix profile install nixpkgs#cachix
            cachix use gerschtli
            cachix use nix-on-droid


            echo "::group::Build command"
            git config --global --add safe.directory "$(pwd)"

            nix ${{ matrix.nix-command }}


            ${{ github.ref == 'refs/heads/master' && inputs.branch == '' && matrix.deploy-spec && '
            echo "::group::Build spec"
            spec="$(nix build --print-out-paths "$DEPLOY_SPEC")"

            echo "::group::Deploy spec"
            cachix push gerschtli "$spec"
            cachix deploy activate "$spec"
            ' || '
            echo "::group::Skip spec deploy"
            ' }}

      - name: Build command (x86_64)
        if: matrix.system == 'x86_64'
        env:
          _system: ${{ matrix.system }}-linux
        run: nix ${{ matrix.nix-command }}

      - name: Deploy cachix-agent spec (x86_64)
        if: matrix.system == 'x86_64' && github.ref == 'refs/heads/master' && inputs.branch == '' && matrix.deploy-spec
        env:
          CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN }}
        run: |
          echo "::group::Build spec"
          spec="$(nix build --print-out-paths "${{ matrix.deploy-spec }}")"

          echo "::group::Deploy spec"
          cachix push gerschtli "$spec"
          cachix deploy activate "$spec"

# vim: set sw=2:
